### ISSUE TITLE
Add general method for defining permissions

### ISSUE THREAD

**Issue by caolan** [hoodiehq/hoodie-plugins-api#33]
This should add a design doc with a validate_doc_update function, something along the lines of:

```js
db.addPermission('ownerWrites', function (newDoc, oldDoc, userCtx) {
    if (oldDoc && oldDoc.createdBy !== userCtx.name) {
        throw 'Only document owner can edit this document';
    }
    else if (newDoc.createdBy !== userCtx.name) {
       throw 'The createdBy property must match your username';
    }
});
```

And to remove a permission:

```js
db.removePermission('ownerWrites');
```

It should throw in the couchdb format for permissions errors: `{unauthorized: error}`

This API would be as an alternative to https://github.com/hoodiehq/hoodie-plugins-api/pull/30

**Comment by boennemann** [comment]
#37
